import type { Song } from './types.js';

export const songs: Song[] = [
  // 60s
  {
    id: 'hey-jude',
    title: 'Hey Jude',
    artist: 'The Beatles',
    year: 1968,
    deezerId: 116348632,
    providerIds: { deezer: 116348632 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '60s',
    genre: ['rock'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'respect',
    title: 'Respect',
    artist: 'Aretha Franklin',
    year: 1967,
    deezerId: 904732,
    providerIds: { deezer: 904732 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '60s',
    genre: ['soul', 'rock'],
    explicit: false,
    packId: 'base',
  },
  // 70s
  {
    id: 'bohemian-rhapsody',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    year: 1975,
    deezerId: 9997018,
    providerIds: {
      deezer: 9997018,
      spotify: '7tFiyTwD0nx5a1eklYtX2J',
      youtube: 'fJ9rUzIMcZQ',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '70s',
    genre: ['rock'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'stayin-alive',
    title: "Stayin' Alive",
    artist: 'Bee Gees',
    year: 1977,
    deezerId: 139138743,
    providerIds: { deezer: 139138743 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '70s',
    genre: ['pop', 'disco'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'hotel-california',
    title: 'Hotel California',
    artist: 'Eagles',
    year: 1977,
    deezerId: 426703682,
    providerIds: { deezer: 426703682 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '70s',
    genre: ['rock'],
    explicit: false,
    packId: 'base',
  },
  // 80s
  {
    id: 'billie-jean',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    year: 1982,
    deezerId: 4603408,
    providerIds: {
      deezer: 4603408,
      spotify: '5ChkMS8OtdzJeqyybCc9R5',
      youtube: 'Zi_XLOBDo_Y',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '80s',
    genre: ['pop'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'sweet-child-o-mine',
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    year: 1987,
    deezerId: 518458172,
    providerIds: { deezer: 518458172 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '80s',
    genre: ['rock'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'dont-you-want-me',
    title: "Don't You Want Me",
    artist: 'The Human League',
    year: 1981,
    deezerId: 3092940,
    providerIds: { deezer: 3092940 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '80s',
    genre: ['electronic', 'pop'],
    explicit: false,
    packId: 'base',
  },
  // 90s
  {
    id: 'smells-like-teen-spirit',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    year: 1991,
    deezerId: 13791930,
    providerIds: {
      deezer: 13791930,
      spotify: '4CeeEOM32jQcH3eN9Q2dGj',
      youtube: 'hTWKbfoikeg',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '90s',
    genre: ['rock'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'baby-one-more-time',
    title: '...Baby One More Time',
    artist: 'Britney Spears',
    year: 1998,
    deezerId: 540175,
    providerIds: { deezer: 540175 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '90s',
    genre: ['pop'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'livin-la-vida-loca',
    title: "Livin' la Vida Loca",
    artist: 'Ricky Martin',
    year: 1999,
    deezerId: 13704591,
    providerIds: { deezer: 13704591 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '90s',
    genre: ['latin', 'pop'],
    explicit: false,
    packId: 'base',
  },
  // 00s
  {
    id: 'crazy-in-love',
    title: 'Crazy In Love',
    artist: 'Beyoncé',
    year: 2003,
    deezerId: 609244,
    providerIds: { deezer: 609244 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '00s',
    genre: ['pop', 'r&b'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'gasolina',
    title: 'Gasolina',
    artist: 'Daddy Yankee',
    year: 2004,
    deezerId: 3165861441,
    providerIds: { deezer: 3165861441 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '00s',
    genre: ['latin', 'reggaeton'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'hey-ya',
    title: 'Hey Ya!',
    artist: 'OutKast',
    year: 2003,
    deezerId: 628266,
    providerIds: { deezer: 628266 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '00s',
    genre: ['pop', 'hip-hop'],
    explicit: false,
    packId: 'base',
  },
  // 10s
  {
    id: 'rolling-in-the-deep',
    title: 'Rolling in the Deep',
    artist: 'Adele',
    year: 2010,
    deezerId: 1174602992,
    providerIds: {
      deezer: 1174602992,
      spotify: '4b9ETkQQuds3gi9yfLC6wx',
      youtube: 'rYEDA3JcQqw',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '10s',
    genre: ['pop', 'soul'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'get-lucky',
    title: 'Get Lucky',
    artist: 'Daft Punk',
    year: 2013,
    deezerId: 66609426,
    providerIds: { deezer: 66609426 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '10s',
    genre: ['electronic', 'pop'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'shape-of-you',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    year: 2017,
    deezerId: 139470659,
    providerIds: {
      deezer: 139470659,
      spotify: '7qiZfU4dY1lWllzX7mPBI3',
      youtube: 'JGwWNGJdvx8',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '10s',
    genre: ['pop'],
    explicit: false,
    packId: 'base',
  },
  // 20s
  {
    id: 'blinding-lights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    year: 2019,
    deezerId: 908604612,
    providerIds: {
      deezer: 908604612,
      spotify: '0VjIjW4GlUZAMYd2vXMi3b',
      youtube: '4NRXx6U8ABQ',
    },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 1,
    decade: '10s',
    genre: ['pop', 'electronic'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'as-it-was',
    title: 'As It Was',
    artist: 'Harry Styles',
    year: 2022,
    deezerId: 1703487577,
    providerIds: { deezer: 1703487577 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '20s',
    genre: ['pop'],
    explicit: false,
    packId: 'base',
  },
  {
    id: 'flowers',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    year: 2023,
    deezerId: 2105158337,
    providerIds: { deezer: 2105158337 },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 2,
    decade: '20s',
    genre: ['pop'],
    explicit: false,
    packId: 'base',
  },
];

export const indieVibesSongs: Song[] = [
  {
    id: 'groupie-leonie-biney',
    title: 'Groupie',
    artist: 'Leonie Biney',
    year: 2025,
    deezerId: 0,
    providerIds: { youtube: 'FHzx_PmaO3Y' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'better-than-nothing-riarosa',
    title: 'Better Than Nothing',
    artist: 'Riarosa',
    year: 2019,
    deezerId: 0,
    providerIds: { youtube: 'X8YKLwPK3Mg' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'your-apartment-wallows',
    title: 'Your Apartment',
    artist: 'Wallows',
    year: 2024,
    deezerId: 0,
    providerIds: { youtube: 'X6amKL3g6f0' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie', 'pop'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'moon-girl-ha-vay',
    title: 'Moon Girl',
    artist: 'Ha Vay',
    year: 2023,
    deezerId: 0,
    providerIds: { youtube: 'Y6KQVbOhN04' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'alrighty-aphrodite-peach-pit',
    title: 'Alrighty Aphrodite',
    artist: 'Peach Pit',
    year: 2018,
    deezerId: 0,
    providerIds: { youtube: 'ICNtZKmQGMw' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'pop'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'cryptograms-deerhunter',
    title: 'Cryptograms',
    artist: 'Deerhunter',
    year: 2007,
    deezerId: 0,
    providerIds: { youtube: 'Ot4Py6BlQnw' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '00s',
    genre: ['indie', 'experimental'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'locket-crumb',
    title: 'Locket',
    artist: 'Crumb',
    year: 2017,
    deezerId: 0,
    providerIds: { youtube: 'BqnG_Ei35JE' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'psychedelic'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'witches-alice-phoebe-lou',
    title: 'Witches',
    artist: 'Alice Phoebe Lou',
    year: 2020,
    deezerId: 0,
    providerIds: { youtube: 'JuklRMZj7CA' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie', 'folk'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'should-have-known-better-sufjan',
    title: 'Should Have Known Better',
    artist: 'Sufjan Stevens',
    year: 2015,
    deezerId: 0,
    providerIds: { youtube: 'lJJT00wqlOo' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'folk'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'juna-clairo',
    title: 'Juna',
    artist: 'Clairo',
    year: 2024,
    deezerId: 0,
    providerIds: { youtube: 'TsxAVFQkXQ8' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie', 'pop'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'flaw-soccer-mommy',
    title: 'Flaw',
    artist: 'Soccer Mommy',
    year: 2018,
    deezerId: 0,
    providerIds: { youtube: 'MU64cMU7QbA' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'rock'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'lemon-local-natives',
    title: 'Lemon',
    artist: 'Local Natives',
    year: 2020,
    deezerId: 0,
    providerIds: { youtube: 'EDnQ2eA971I' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie', 'folk'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'pristine-snail-mail',
    title: 'Pristine',
    artist: 'Snail Mail',
    year: 2018,
    deezerId: 0,
    providerIds: { youtube: 's7tnTucP1UM' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'rock'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'archie-marry-me-alvvays',
    title: 'Archie, Marry Me',
    artist: 'Alvvays',
    year: 2014,
    deezerId: 0,
    providerIds: { youtube: 'ZAn3JdtSrnY' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '10s',
    genre: ['indie', 'pop'],
    explicit: false,
    packId: 'indie-vibes',
  },
  {
    id: 'can-i-believe-you-fleet-foxes',
    title: 'Can I Believe You',
    artist: 'Fleet Foxes',
    year: 2020,
    deezerId: 0,
    providerIds: { youtube: 'L2E2DpWO3-Y' },
    previewUrl: '',
    hookStart: 0,
    hookDuration: 15,
    difficulty: 3,
    decade: '20s',
    genre: ['indie', 'folk'],
    explicit: false,
    packId: 'indie-vibes',
  },
];

export const allSongs = [...songs, ...indieVibesSongs];

export const packs = [
  {
    id: 'base',
    name: 'Pack Base',
    description: '20 hits de todos los tiempos (1967–2023)',
    songIds: songs.map((s) => s.id),
  },
  {
    id: 'indie-vibes',
    name: 'Indie Vibes',
    description: '15 canciones indie/alternativas para probar mobile',
    songIds: indieVibesSongs.map((s) => s.id),
  },
];
